.editorconfig
.github/actions/run-with-avd/action.yml
.github/actions/setup/action.yml
.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/dependency-submission.yml
.github/workflows/release.yml
CONTRIBUTING.md
build.gradle.kts
demo-app/build.gradle.kts
demo-app/demo_app.podspec
gradle/libs.versions.toml
iosApp/Podfile.lock
lib/maplibre-compose/build.gradle.kts

for #10 
also some misc CI / formatter config while I'm here

build/ci: configure jgitver for automated versioning and configure misc ci stuff

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/CircleLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HeatmapLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HillshadeLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/LineLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/RasterLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt

also, remove onClick, onLongClick parameters for RasterLayer, HillshadeLayer, they are not Feature-based

amend documentation for onClick, onLongClick on layers

---

gradle.properties
iosApp/iosApp.xcodeproj/project.pbxproj
lib/maplibre-compose/MODULE.md
lib/maplibre-compose/build.gradle.kts

Updates Dokka configuration and removes unused iOS build phase
- Configures Dokka documentation with source links to GitHub repository
- Adds external documentation links for spatial-k and maplibre-native dependencies
- Adds MODULE.md with package documentation

Configure dokka documentation settings

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/StyleSwitcherDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/compose/IosMapView.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt

fixes #47, we were using inconsistent units between ios and android
for now I'm making ios match android and use pixel space, but I intend to refactor this all to dp space afterwards
also adds some missing stuff to camerastate, and some temporary logging to one of the demos (will remove after the refactor mentioned above)

translate ios screen location to pixel location for now to fix #47

---

build.gradle.kts
docs/docs/index.md
docs/mkdocs.yml
gradle/libs.versions.toml

install mkdocs

---

CONTRIBUTING.md
README.md
build.gradle.kts
docs/docs/api/index.html
docs/docs/getting-started.md
docs/docs/index.md
docs/mkdocs.yml
lib/maplibre-compose/MODULE.md

docs: write getting started guide in mkdocs

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/VisibleRegion.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

also added a new method and consolidated several method overloads into one, after checking in the native source code that the behavior doesn't change.

Docs for camera state

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt

fix: make layer onclick trigger in actual layer order

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/StyleSwitcherDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/util.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/getBaseSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberGeoJsonSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberRasterSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberUserSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberVectorSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonOptions.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt

also,
- added the tileSize parameter for RasterSource
- remember*Source return typed *

some docs for Sources

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/library-conventions.gradle.kts
demo-app/build.gradle.kts
lib/maplibre-compose/build.gradle.kts

also centralize spotless config

build: start factoring out a gradle convention plugin

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionValue.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt

Adds opt-in annotations for platform-specific APIs

 feat: add platform-specific API annotations

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt

You missed two functions in #118

move missed function into FeatureScope

---

demo-app/src/commonMain/composeResources/files/data/colorful.json
demo-app/src/commonMain/composeResources/files/data/eclipse.json
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/util.kt

added some local style examples

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/util.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionValue.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt

textOffset isn't supported yet; gotta think more on how to handle that one as apparently expressions aren't allowed inside list literals

feat: support TextUnit on most sp/em properties

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/EdgeToEdgeDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/docs/Material3.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/ScaleBar.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidScaleBar.kt

closes https://github.com/sargunv/maplibre-compose/issues/157

feat: add Google open source scale bar

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/EdgeToEdgeDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/docs/Material3.kt
docs/docs/material3.md
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/CompassButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/ScaleBar.kt

feat: add disappearing compass button

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt

related: https://github.com/sargunv/maplibre-compose/issues/143

disable broken property and fix some docs

---

lib/maplibre-compose-material3/src/commonMain/composeResources/values/strings.xml
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/CompassButton.kt

closes https://github.com/sargunv/maplibre-compose/issues/135

create string resources for content description of material3 controls

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/MarkersDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt

closes https://github.com/sargunv/maplibre-compose/issues/180

feat: support TextUnit in format

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/MarkersDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/ImageManager.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/ReferenceCounter.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/SourceManager.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/Expression.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt

feat: support Painter in image expressions

---

lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/ExpressionContext.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/ast/BitmapLiteral.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/ast/PainterLiteral.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/image.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidStyle.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/ImageManager.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/LayerPropertyCompiler.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/Style.kt
lib/maplibre-compose/src/commonTest/kotlin/dev/sargunv/maplibrecompose/compose/FakeStyle.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosStyle.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt

feat: add support for image sdf and painter size

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/util.kt
lib/compose-html-interop/src/commonMain/kotlin/dev/sargunv/composehtmlinterop/HtmlElement.kt
lib/compose-html-interop/src/commonMain/kotlin/dev/sargunv/composehtmlinterop/util.kt
lib/compose-html-interop/src/jsMain/kotlin/dev/sargunv/composehtmlinterop/util.js.kt
lib/compose-html-interop/src/wasmJsMain/kotlin/dev/sargunv/composehtmlinterop/util.wasmJs.kt
lib/maplibre-compose/src/jsMain/kotlin/dev/sargunv/maplibrecompose/compose/WebMapView.kt

TODO: figure out passing through touch / mouse interaction before we can actually enable it for the map

support punching a hole in Compose UI to blend with HTMLElement

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/EdgeToEdgeDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt
lib/maplibre-compose/src/commonTest/kotlin/dev/sargunv/maplibrecompose/compose/StyleNodeTest.kt

fix crash on parsing URLs with templating

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt

There was a little bug, long click was not working, this PR fixes it

OnMapLongClickListener on Android bug fix

---

buildSrc/build.gradle.kts
settings.gradle.kts

So I don't have to install the right JDK version on every machine I work with

configure foojay toolchain resolver

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt

Camera padding fix

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/SuperimposingPopupPositionProvider.kt

- fixed movement/extension of popup
- added padding at the end of the attribution popup
- made attribution popup customizable
Developed on top of #293

Attribution Button improvements

---

demo-app/src/commonMain/composeResources/files/styles/empty.json
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/app.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/LocalTilesDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberRasterSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberVectorSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/Defaults.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonOptions.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/TileCoordinateSystem.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/TileSetOptions.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/jsMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/jsMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt

Resolves #241 (for raster tiles, vector todo)

feat: add support for programatically configuring tile set

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/app.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/LocalTilesDemo.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt

local tile demo now working on android; now it's a fully functional example for #314 and #302
also hacked the scale bar to be more appropriate for the fantasy map

fix: local tiles on android

---

lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/decision.kt

Fixes https://github.com/sargunv/maplibre-compose/issues/310. We work around the upstream bug by cascading our cases so each has only one condition and a fallback.

fix: crash on iOS with multiple conditions in iconImage

---

lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/decision.kt

https://github.com/maplibre/maplibre-native/issues/3477

Add upstream bug report to comment.

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraStateSaver.kt

fix: camerastate saver should save dp as primitive

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

fix: recognize long press correctly on delay, not on release, on ios

---

.github/FUNDING.yml
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
LICENSE
SECURITY.md

Merge once we have both board member approvals in https://github.com/maplibre/maplibre/issues/441

chore: update GH special files to meet MapLibre onboarding requirements

---

gradle/libs.versions.toml

chore: update compose

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt

See comment thread here: https://github.com/maplibre/maplibre-compose/pull/349#discussion_r2106228429
This PR adds an overload for the attribution button for the caller to manage the behavior of the button, rather than the default behavior (start expanded, dismiss on interaction).

refactor attribution button to allow caller to manage state if desired

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/StyleState.kt

now that we have state, we don't need the imperative function

make sources state a map of id to source, and remove imperative function for getting source by id

---

lib/maplibre-compose/build.gradle.kts
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/OfflineRegion.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/OfflineRegionManager.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/util.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/OfflineRegion.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/OfflineRegionManager.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/util.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt
lib/maplibre-compose/src/maplibreNativeMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/api.kt
lib/maplibre-compose/src/nativeInterop/cinterop/observer.def

partial impl of #22 for ios
todo

wip: implement offline region manager for ios

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/StyleSwitcherDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/util.kt

the scrolling tab row is getting a bit ridiculous, but I'm overhauling the demo app anyway so that'll be dealt with later

add protomaps styles too

---

.gitignore
CLAUDE.md

planning on using this to try to generate the tedious JS map styling bindings and possibly some tests
https://www.anthropic.com/engineering/claude-code-best-practices

set up claude code

---

lib/maplibre-native-bindings-jni/build.gradle.kts

do not publish empty variants

---

lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapAdapter.kt
lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/util/conversions.kt
lib/maplibre-native-bindings-jni/src/main/cpp/maplibre_map.cpp

No functional changes; just simplifying this pattern and reorganizing things to make it easier to implement the rest

native core: simplify jni try/catch pattern for maplibre_map.cpp

---

lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapAdapter.kt
lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/util/conversions.kt
lib/maplibre-native-bindings-jni/cmake/target.cmake
lib/maplibre-native-bindings-jni/src/main/cpp/conversions.cpp
lib/maplibre-native-bindings-jni/src/main/cpp/conversions.hpp
lib/maplibre-native-bindings-jni/src/main/cpp/maplibre_util_projection.cpp
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/util/Projection.kt

desktop: project to/from screen/world position

---

demo-app/src/commonMain/kotlin/org/maplibre/compose/demoapp/DemoMap.kt
demo-app/src/commonMain/kotlin/org/maplibre/compose/demoapp/DemoState.kt
demo-app/src/commonMain/kotlin/org/maplibre/compose/demoapp/design/SwitchListItem.kt
demo-app/src/desktopMain/kotlin/org/maplibre/compose/demoapp/demos/GestureOptionsDemo.desktop.kt
demo-app/src/desktopMain/kotlin/org/maplibre/compose/demoapp/util/Platform.desktop.kt
lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapAdapter.kt
lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapView.kt
lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/GestureOptions.kt
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/map/MapControls.kt

desktop: implement gesture options + demo
