maplibre/maplibre-compose

maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/BackgroundLayer.kt
maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/CircleLayer.kt
maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/FillExtrusionLayer.kt
maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/FillLayer.kt
maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/HeatmapLayer.kt
maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/HillshadeLayer.kt
maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/LineLayer.kt
maplibre-kmp/src/commonMain/kotlin/dev/sargunv/maplibrekmp/compose/layer/SymbolLayer.kt

to be more consistent. The order:
1. common properties (sortKey, translate, opacity, ...)
2. colors (color, pattern, gradients, ...)
3. defining shapes (radius, strokes, outlines, heights)
4. layer specifics
For the symbol layer, also
1. common properties
2. symbol properties,
3. icon properties
4. text properties
The icon and text properties are sorted in a consistent manner:
1. content (image / text)
2. colors
3. layout
4. anchoring
5. collision
6. translate
---
I hereby contribute this under the terms of the BSD license.

reorder layer params

---

gradle/libs.versions.toml

It would be nice to support a wider range of Android devices by setting minSdk to 21. Treat it as a suggestion, for now, it compiles successfully with minSdk 21, but I don't know if there are plans to use any functionality available only on SDK 24 and above, so feel free to reject the PR.

Change Android minSdk to 21

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/AnimatedLayerDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/StyleManager.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/Anchor.kt

I documented the anchors.
But I also:
- replaced `WithLayerId` sealed interface with something internal because actually it is internal. When it is internal, no need to have it on the interface (and document it)
- renamed composable anchor functions so that they don't conflict or can be mistaken with the data classes of the same name
What do you think?

document Anchors

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt

It's useful to have access to screenLocationFromPosition outside of the library. A common use case is when someone wants to query rendered features around a certain point, they need the screen location of that point, for example:
``` kotlin
FloatingActionButton(
onClick = {
val position = Position(latitude = 45.521, longitude = -122.675)
val queryCenter = cameraState.screenLocationFromPosition(position)
queryCenter?.let {
val queryRect = Rect(queryCenter.x - 20, queryCenter.y - 20, queryCenter.x + 20, queryCenter.y + 20)
val result = cameraState.queryRenderedFeatures(queryRect)
}
})
```
By the way, what are your thoughts on pull requests without creating the issue first? Sometimes when the change is so tiny, I find it easier to make a pull request than create the issue, and you can treat …

Expose screenLocationFromPosition to CameraState

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/StyleSwitcherDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/util.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/MaplibreMap.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt

Changed screen coordinate handling from raw pixels to density-independent units (Dp).
Key changes:
- Replaced Offset with DpOffset for screen coordinates
- Replaced Rect with DpRect for screen regions
- Updated coordinate conversion utilities to handle density-independent units
- Removed debug click handling code from StyleSwitcherDemo
closes #49

feature: migrate screen coordinates from Offset to DpOffset

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/Expression.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt

small, easy win to help with #42 
Changed `ofNull()` function to a property `ofNull` to better reflect its constant nature, as it always returns the same `Expression<Nothing?>` instance. Updated the `nil()` function to reference the new property.

convert Expression.ofNull to property as an easy win to reduce allocations

---

demo-app/build.gradle.kts
lib/maplibre-compose/build.gradle.kts
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt

* Enable the strong skipping feature flag in the Compose compiler for both the demo app and library modules.
* Enable compose compiler reports. I wanted to commit these so I could review their diffs in PRs, but they don't seem to be stable. So I put them in the build directory instead. 
* Remove the `@Stable` annotation from CameraState as it was unnecessary (there's no `equals` on it, and strong skipping is fine here)

build: enable strong skipping

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/FrameRateDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/util/PlatformUtils.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/util/PlatformUtils.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/PlatformUtils.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt

Detect and use system refresh rate for map rendering
This change improves frame rate handling by detecting the device's native refresh rate instead of using a hardcoded value. The maximum FPS now defaults to the system's refresh rate on both Android and iOS platforms.
Key changes:
- Added `PlatformUtils` to detect system refresh rate on Android and iOS
- Updated `FrameRateDemo` to use system refresh rate as the upper bound
- Set map's default `maximumFps` to match the system refresh rate

feature: default to system refresh rate for map fps

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/AnimatedLayerDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/KermitLoggerDefinition.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/Expression.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

Adds logging integration with MapLibre's native logging systems on both Android and iOS platforms. On Android, implements a `KermitLoggerDefinition` to bridge Kermit logging with MapLibre's logging system. On iOS, configures MapLibre's logging system to forward logs to Kermit. Also includes a fix for negative number handling in Expression creation.
relates to #38 but doesn't quite resolve it, as the http logger on android seems to be distinct from the LoggerDefinition configuration

feature: integrate Kermit logging with native map SDKs

---

demo-app/src/androidMain/kotlin/dev/sargunv/maplibrecompose/demoapp/MainActivity.kt
lib/maplibre-compose/build.gradle.kts

this'll allow a workaround for https://github.com/sargunv/maplibre-compose/issues/38 by exposing the native sdk in android sourcesets. will solve the full logging issue later

build: make maplibre dependencies api instead of implementation

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/AnimatedLayerDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraFollowDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/CircleLayer.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/FillLayer.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/HeatmapLayer.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/LineLayer.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/CircleLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HeatmapLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/LineLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/CircleLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/FillLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/HeatmapLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/LineLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/CircleLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/FillLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/HeatmapLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/LineLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt

1. consistent with other Compose API
2. easier to see from signature which type is expected. It is often not clear from the name alone which unit is expected. E.g. `blur` in most layers is in `dp`, but in `CircleLayer`, it is actually some kind of fraction. Offsets are usually in `dp`, but any text offsets are in `em` (i.e. relative to the font size). `iconSize` is also not in `dp` but a fraction.
3. shorter documentation comments (Units don't need to be mentioned in the comments)
In the `SymbolLayer`, actually all offsets concerning text are en `em`: `textOffset`, `textRadialOffset`, `textVariableAnchorOffset` but also `texMaxWidth` and `textLineHeight`.
It would be possible to add another value class named `Em` and allow these to be created with an expression like `10.em` (like for …

use compose Dp for pixel sizes

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/BackgroundLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/CircleLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HeatmapLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HillshadeLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/LineLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/RasterLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/Expression.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/utils.kt

also eliminate some superfluous import aliases

create default vals for complex defaults, and precalculate small floats expressions in .05 increments

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraFollowDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/CameraMoveReason.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/MaplibreMap.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

Added camera movement tracking to improve map interaction. To showcase this, in the camera follow demo, the camera now stops following when users interact with the map through gestures like panning, zooming, rotating, or tilting. Users can resume following with a new "Follow" button.
closes #12

feat: add camera move reason tracking

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/CameraMoveReason.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/CameraPosition.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/GestureSettings.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/OrnamentSettings.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonOptions.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt

also, I noticed that on iOS, there doesn't seem to be an option to turn on/off the
- double tap to zoom in
- double tap, then hold and drag up or down to zoom
gestures separately from zooming via gesture at all.
So, to achieve the same behavior on all platforms, on Android, we need to set all these separate settings to true/false when the allow-zoom setting changes.

document some settings

---

.github/workflows/ci.yml
.github/workflows/release.yml
build.gradle.kts
docs/docs/index.md

Updates documentation generation to combine API reference and user guide into a single documentation site. The API reference is now accessible through a link on the main documentation page, and both the API reference and user guide are built into a unified directory structure.
The changes standardize the documentation output path to `build/docs` and introduce a new `generateDocs` Gradle task that coordinates the generation of both documentation types.
See #17

combine dokka and mkdocs output into single docs site

---

README.md

- Add badges for Documentation and API Reference
- Move detailed usage instructions to the documentation site
- Link to the Getting Started guide for setup instructions

docs: reorganize readme and add documentation links

---

build.gradle.kts
demo-app/build.gradle.kts
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
lib/maplibre-compose/build.gradle.kts

Updates Gradle dependencies and configuration
- Upgrades Gradle to 8.10
- Upgrades Ktor to 3.0.2
- Updates Android SDK targets to version 35
- Reorganizes version catalog structure with clearer grouping
- Extracts iOS deployment target to version catalog
- Fixes library reference naming to follow consistent pattern

build: upgrade dependencies and organize gradle version catalog

---

demo-app/build.gradle.kts
lib/maplibre-compose/build.gradle.kts
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/util/PlatformUtils.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/LayerPropertyEnum.kt

one api change, `Expression<Dp>.value` is now `Expression<Dp>.asNumber()` to avoid a shadowing warning

build: fix warnings and enable allWarningsAsErrors

---

build.gradle.kts
docs/docs/getting-started.md
gradle/libs.versions.toml

Adds documentation for using MapLibre's Vulkan backend on Android and updates MapLibre Android dependency to 11.7.0-pre1.

docs: add Vulkan setup instructions and update MapLibre version

---

gradle/libs.versions.toml

Updates MapLibre Android SDK from pre-release version 11.7.0-pre1 to stable release 11.7.0

build: upgrade MapLibre Android to 11.7.0

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/CircleLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HeatmapLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/LineLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/LayerPropertyEnum.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/utils.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonOptions.kt

- Added documentation comments
- Added `// regions` (used to group code and collapse/expand these sections in IDEs such as VSCode or IntelliJ)
- Fixed parameter names of `slice`: `length` was wrong, it is `endIndex` ([see source code](https://github.com/maplibre/maplibre-style-spec/blob/main/src/expression/definitions/slice.ts#L22))
- Fixed order of `fallback` parameter for `match` and `case` - it was inconsistent (even though it is consistent in the spec)
- Documentation claims that "==" and "!=" only works for Booleans, Strings, Numbers, so I added overloads for these types instead of for * ([see source code](https://github.com/maplibre/maplibre-style-spec/blob/7604485fc0b66394b62a44fa9d4cd9816d7d8858/src/expression/definitions/comparison.ts#L29-L30))
- Documentation claims that …

Expressions documentation and refinement

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt

Renamed variable binding functions to be more descriptive:
- `let` -> `withVariable`
- `var` -> `useVariable`
These new names better reflect their purpose in the expression DSL and avoid potential naming conflicts with Kotlin keywords.
related: https://github.com/sargunv/maplibre-compose/pull/107

refactor: rename let/var to withVariable/useVariable

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/Expression.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt

Improved type safety for expressions by removing implicit auto-casting on get and variables. Variables now have a typed definition, and get returns an unknown expression that must explicitly be cast or validated to narrow the type.

refactor: make expression type casting more explicit

---

build.gradle.kts
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/EdgeToEdgeDemo.kt
gradle/libs.versions.toml
lib/maplibre-compose/build.gradle.kts
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/compose/AndroidMapView.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidScaleBar.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/OrnamentSettings.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

Added scale bar support to MapLibre Compose
This PR adds a scale bar ornament to MapLibre Compose maps. The scale bar can be enabled/disabled and positioned using the `OrnamentSettings` API, similar to other ornaments like the compass and attribution button.
Key changes:
- Added scale bar plugin dependency for Android
- Added `isScaleBarEnabled` and `scaleBarAlignment` properties to `OrnamentSettings`
- Implemented scale bar positioning and padding logic for both Android and iOS platforms
The scale bar grows rightward on Android and adapts to its alignment on iOS. Default position is top-start (top-left).

feat: add scale bar ornament

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/app.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/EdgeToEdgeDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidScaleBar.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/StyleState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/controls/AttributionButton.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/controls/AttributionDialog.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/controls/CompassButton.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/AttributionLink.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/commonTest/kotlin/dev/sargunv/maplibrecompose/compose/StyleManagerTest.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/util/util.kt

Key changes:
- Created new `AttributionButton` and `AttributionDialog` components
- Added `StyleState` to track and expose style-related information
- Implemented attribution link extraction on Android and iOS
The dialog doesn't extract non-link text from the attribution. This is mirroring the Android SDK's functionality. The iOS SDK's attribution dialog displays non-link text as a button that doesn't work, so I figured it's probably not important.

feat: add material3 attribution button and dialog

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/FrameRateDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/util.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt

This would be the last item of my documentation crusade.
This is draft because there are two open questions:
1. @sargunv sure it should be `MaplibreMap` and not `MapLibreMap`? MapLibre is usually referred to like that
2. the `onFpsChanged` listener/callback is documented in Android to actually be called *on every frame*. I am currently waiting for confirmation that the documentation is indeed correct. If it is correct, this should probably be renamed.

document MapLibreMap

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionScope.kt

It bugged me that the string functions like length(), indexOf(), substring() etc. are not in the "String" region, so I sorted it a bit:
- remove "Lookup" section
- add sections "List", "Map", sort the functions into these
- move "String" section up, right next to "List" and "Map" and put the related functions in there
No other changes, just changed the order of functions in that file.

Sort functions in fitting regions

---

gradle/libs.versions.toml

Updates Dokka Gradle plugin from 2.0.0-Beta to 2.0.0 stable release

chore: update dokka to 2.0.0

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionValue.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt

Add new `ScalarValue<TextUnit>` and `const` functions for the unit. There's a `@Composable` one to provide font scaling automatically. If the provided text unit is in ems, it's considered relative to 16sp, the default font size of the map.

feat: support text scaling (sp instead of dp)

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/RasterLayer.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/RasterLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionValue.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/RasterLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/RasterLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt

tweaking things from https://github.com/sargunv/maplibre-compose/pull/134
* update scalar expression naming to SpValue and MillisecondsValue to better reflect the actual internal representation
* update SymbolLayer in core to accept a DpValue expression, matching what the platform SDKs expect
* update the expression DSL to simplify the TextUnit to Expression<SpValue> conversion
* internal representation of an SpValue is now in sp instead of dp
* and conversion to Expression<DpValue> is done at the boundary between the SymbolLayer composable and the core wrapper
* link the upstream issue for font scaling

refactor: tweak font scaling api

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/Expression.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionValue.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/utils.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt

it seems literal lists can't have expressions inside, so updating the expressions DSL typing

fix: disallow expressions inside literal lists/maps

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt

Fixed incorrect property name when setting text variable anchor offset in iOS symbol layer implementation. The property was incorrectly set as `textVariableAnchor` instead of `textVariableAnchorOffset`.

fix: correct textVariableAnchor property name

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionValue.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt

This won't actually work until https://github.com/maplibre/maplibre-native/issues/3100 is fixed, but might as well write the types and DSL for it

feat: support for textVariableAnchorOffset (does not work yet)

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/expression/ExpressionsDsl.kt

chose `$` because Kotlin users are unlikely to use it in strings if they can help it

feat: reserve variable names starting with $

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraStateDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/EdgeToEdgeDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/MaplibreMap.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

going to use this for a composable scale bar
unsure if density calculation is correct; will confirm with a scale bar implementation before release

feat: add state for meters per dp at camera target

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/app.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/AnimatedLayerDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraFollowDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraStateDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/EdgeToEdgeDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/FrameRateDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/StyleSwitcherDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/docs/Layers.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/docs/Material3.kt
docs/docs/material3.md
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt

closes #156 
map composables (layers) are the only map content now, like it was before
overlay UI goes next to the map in a shared box
this is similar to the Google Maps Compose API

feat: redo map content api

---

lib/maplibre-compose-material3/src/commonMain/composeResources/values-ar/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-av/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-ba/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-be/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-bg/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-ce/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-cu/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-cv/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-es/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-hy/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-ja/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-ka/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-kk/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-ky/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-mk/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-mn/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-ru/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-tg/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-th/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-tt/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-uk/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values-zh/strings.xml
lib/maplibre-compose-material3/src/commonMain/composeResources/values/strings.xml
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/ScaleBar.kt

Researched by looking at all articles in all languages linked from https://en.wikipedia.org/wiki/Metre 😅
Only added strings.xml for languages that have an ISO 639-1 or ISO 639-2 code. (I.e. not ISO 639-3 because[ that isn't supported anyway](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-multiplatform-resources-setup.html#language-and-regional-qualifiers))
"m" should actually be quite understood anywhere, but some languages have an abbreviation in their own script that is preferred over the international symbol ("m").
There are no translations for feet, because feet is only really used in the US, i.e. in an English-speaking country. Hence, in other languages, an abbreviation doesn't really exist.

add localized abbreviations for m/km

---

.github/workflows/ci.yml
.github/workflows/daily.yml

publishing snapshots sometimes fails when I merge many PRs in quick succession. let's switch to publishing at most once a day

ci: move snapshots and dependency submission to daily workflow

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/AnimatedLayerDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/MarkersDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/docs/Layers.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/collections.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/decision.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/feature.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/format.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/image.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/literals.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/math.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/ramps.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/string.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/types.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/variables.kt

feat: Add bare Kotlin type overloads for expression functions

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraStateDemo.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/MaplibreMap.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

this'll be useful as a workaround for upstream issues:
* https://github.com/maplibre/maplibre-native/issues/3107
* https://github.com/maplibre/maplibre-native/issues/3105
* https://github.com/maplibre/maplibre-native/issues/3104

feat: allow bounding the zoom and pitch state

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/app.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/FrameRateDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/util.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/compose/AndroidMapView.kt

unrelated: renamed isNative to usesMaplibreNative

fix: use texture mode on android to fix compose animations

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/compose/AndroidMapView.kt

Disabled texture mode again in MapLibre's Android map view to improve rendering performance. This has caveats; see #15. A future PR will make this an opt-in option instead, see #217 
previously enabled in #214

perf: disable texture mode on android

---

.github/workflows/ci.yml
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/LayerManager.kt

Run Android instrumentation tests against API levels 24 and 35, and fix a compatibility issue by using removeAt instead of removeLast.
fixes #224

fix: removeAt instead of removeLast for SDK <35 compatibility

---

demo-app/build.gradle.kts
gradle.properties
lib/maplibre-compose-expressions/build.gradle.kts
lib/maplibre-compose-material3/build.gradle.kts
lib/maplibre-compose/build.gradle.kts

Previously we used whatever target we built with (23). But this is a library, so we should be compatible with currently supported LTS versions.
fixes #223

fix: configure JVM target to a reasonable LTS (11)

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/jsMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt

the `text-overla`p property for the symbol layer had the wrong type. (It's not functional currently anyway, though, because it is not supported on MapLibre-native. But on MapLibre-Js it is supported)

fix type for text-overlap layer property

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util.kt

after all, the `defaultScaleBarMeasures` is now called every frame.
(If it wasn't `@Composable`, it could also be `remember`ed)
---
I was previously looking into performance improvements on the scalebar, after all, quite a lot is going on there. But basically any attempt to let the scalebar compose less often is sabotaged by the fact that any change in latitude or zoom will make it recompose anyway, as the `metersPerDp` changes.
`metersPerDp` could maybe be rounded, the trick would be to find out at which precision it starts to matter (i.e. be visible on the scalebar). Then, it would generally not recompose when scrolling around in an area, only when one zooms.

scale bar: slight performance improvement

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/CompassButton.kt

As discussed in #250, I made Compass Button more customizable:
- allowed setting the size of the button
- allowed setting drawable of the needle
In addition, 2 changes that seemed reasonable:
- allowed setting content description of DisappearingCompassButton
- set the default content description of CompassButton to string resource, instead of hardcoded string

Made CompassButton more customizable

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidStyle.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/StyleState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosStyle.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/RasterSource.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt
lib/maplibre-compose/src/jsMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt

Related to #39, but not fixing the issue entirely, as the implementations are only for Android. I don't have access to a Mac right now, so I can't implement it for iOS.
Example of usage:
``` kotlin
val vectorSource = styleState.getSource("openmaptiles") as? VectorSource
val features = vectorSource?.querySourceFeatures(setOf("landuse"), null)
```
The first commit was to make it possible to cast Source to VectorSource, GeoJsonSource, and RasterSource. Exposed `getSource()` and `getSources()` make it possible to get a source outside of the Composable function as opposed to `getBaseSource()`

Getting specific type of source, querying source features on android and expose sources

---

demo-app/src/commonMain/composeResources/files/styles/colorful.json
demo-app/src/commonMain/composeResources/files/styles/eclipse.json

I noticed that the eclipse and the colorful styles stopped working on Style Switcher Demo. It happened because of the broken URLs to sprites and glyphs. I took new ones from [versatiles-style](https://github.com/versatiles-org/versatiles-style)

Fixed local styles used in Style Switcher Demo

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/compose/AndroidMapView.kt

I encountered a bug on Android which you can see in the video below.
The camera position is set with zoom 8, and the scale bar is disabled, but after launching an app, for a split second, you can see a map on zoom 0 with a scalebar, after that, it switches to the right settings.
https://github.com/user-attachments/assets/21c40546-23a3-4780-8987-5809e5cf0b94
I figured out that the cause of this behaviour was a delay between `mapView.getMapAsync()` and `update()`.
So what exactly was happening:
1. When `AndroidView()` composable was called for the first time, it called `factory` parameter, which called asynchronous `mapView.getMapAsync()`
2. `update` parameter of `AndroidView()` composable was called, but `currentMap` was null, so it didn't proceed.
3. After some time, …

Fixed delay between loading default map and applying user settings

---

lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/ramps.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/value/unions.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/value/values.kt

A breaking change because name of public class is changed, hence v0.7.0.

solve typo: Interpolateable -> Interpolatable

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

Resolves #298 
The fix adds the necessary view reference when performing coordinate conversion from screen location to map position in iOS. This ensures that the conversion process has access to all required context information to accurately translate screen coordinates to geographical positions on the map.
The implementation properly references the UIView when calling the conversion methods, ensuring that the MapLibre native iOS SDK has all the context it needs to perform accurate coordinate transformations.
- iOS-specific coordinate conversion code
- Screen-to-map position translation functionality
The fix has been tested on iOS devices and simulators, confirming that:
- Screen coordinates are now correctly converted to map positions
- The functionality works consistently across …

Fix for Missing View Reference in iOS Position Conversion

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt

Currently `CameraState.awaitInitialized()` doesn't work as expected. When it receives `mapAttachSignal`, the `map` variable is still null, so calling `requireMap()` after `CameraState.awaitInitialized()` still crashes. It happens because the `mapAttachSignal` is send before setting `map` variable. This PR fixes this problem.

Update map before sending map attach signal

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraStateDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt

Implements a public isCameraMoving property on CameraState that tracks whether the camera is currently being animated or moved by the user. This is updated via onCameraMoveStarted and onCameraMoveEnded.
A visual cell was added to the CameraStateDemo for testing and demonstration.

Add isCameraMoving to CameraState to indicate ongoing camera movement

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/compose/MeasuredBox.kt

Similar to #328
Correctly updating the size in IosMap is essential to having working `getVisibleRegion()` and `toMLNMapCamera()` (I noticed some zoom jumps when animating camera position).
This PR fixes it.
It looks like size wasn't correctly updated, because `MeasuredBox` was recomposed only the first time `onGloballyPositioned` was called (when it still didn't update the size). Then, when the size was updated, `MeasuredBox` wasn't recomposed, resulting in having the size of the previous screen orientation.

Fixed chaging size on ios

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

I noticed that on iOS when I was animating the camera to the bounding box, the padding was not applied. This PR fixes this problem.

[iOS] Fixed padding when animating camera to bounding box

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/LocalTilesDemo.kt
gradle/libs.versions.toml
lib/maplibre-compose-material3/build.gradle.kts
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/ScaleBar.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/ScaleBarMeasure.kt

based on #234, but only the material3 part; not pulling this library into core rn.
This overhauls the `ScaleBarMeasure` interface to support `Length` units from [alchemist](https://github.com/kevincianfarini/alchemist). As a demo, I also updated the local tiles (fantasy map) demo with a fictional unit.

feat: overhaul scale bar measure api with alchemist library

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/LocalTilesDemo.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/StyleState.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/StyleNode.kt

Fixes #353 
I added attribution to the local tile set, and noticed the style state wasn't updating for sources added via the style composition; only from the base style.

fix: update style state for programmatic styles

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt

fix #355 by just caching the attribution links (we already do this on android)
still unsure of the root cause

fix: work around native crash with retrieving ios attribution info during rotation

---

docs/docs/getting-started.md

Looks like the Kotlin Gradle plugin doesn't support a configuration lambda for dependencies from the version catalog. So, the user needs to pass a string.

docs: fix android vulkan setup guide

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/SuperimposingPopupPositionProvider.kt

Marges into #293
Fixes https://github.com/maplibre/maplibre-compose/pull/293#issuecomment-2888529761
It wasn't a compose bug as I initially thought, and it was happening both on Android and iOS. It occurred on iOS, because of a different screen size. It was actually a rare case when the popup's width was larger than the screen, but not large enough to properly break line. In short. Because we were setting the width which was calculated in `SuperimposingPopupPositionProvider` based on the content size, it couldn't properly update it.
This PR fixes this.
There is a small issue with this that I couldn't figure out how to fix, but it's not a big deal, I guess. When opening a map, sometimes for a split second, you can see a change in the popup from 1 line to 2 lines. …

Attribution button stretch fix

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/feature.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonOptions.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/GeoJsonSource.kt

Supersedes #237. Partial fix for #236.
I managed to get this working on iOS, but it still crashes on Android with a segfault. Reported upstream, https://github.com/maplibre/maplibre-native/issues/3493. Interestingly, it doesn't crash if the mapper is a literal, like `const(1)`. In that case, it seems to work on Android too, so I think we've got the usage right, it's just broken upstream.
Take the example from the docs, and use it in the cluster properties demo (instead of point count).

Document and fix clusterproperties interface

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/CameraFollowDemo.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/Dp.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/Intersection.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/Modifier.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/PointerPinButton.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt

Add a new widget to the material3 library. A pointer pin:
https://github.com/user-attachments/assets/da7cb4d5-023d-40cd-b6c8-7d162b9e5652
- Test on both platforms.
- Might want to test different sizes for the pointer pin content, too. 
- Might want to check if it works fine with rotation and tilt
- Might want to check if it works fine in edge-to-edge
This pull request primarily adds a feature.
To my knowledge, I am not making breaking changes.
I don't have access to a macOS device to test iOS changes right now.
I have tested the changes insofar as can be seen in the video (Android only).

Add pointer pin widget

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/docs/Interaction.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/PointerPinButton.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraProjection.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/CameraState.kt

See discussion in this comment thread: https://github.com/maplibre/maplibre-compose/pull/364#discussion_r2106361485
This PR moves all the APIs for imperatively querying the camera projection to a new CameraProjection class, and provides a reference via a State that gets initialized when the map is attached. So the most intuitive way to use this API is now also correct wrt awaiting and recomposing on initialization.

refactor camera state initialization api

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/app.kt
lib/maplibre-compose-material3/src/androidMain/kotlin/dev/sargunv/maplibrecompose/material3/util/util.android.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/CompassButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/DisappearingScaleBar.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/PointerPinButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/ScaleBar.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/AngleMath.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/Arrangement.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/ColorScheme.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/Dp.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/DrawScope.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/Intersection.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/Modifier.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/measures.kt
lib/maplibre-compose-material3/src/commonTest/kotlin/dev/sargunv/maplibrecompose/material3/util/AngleMathTest.kt
lib/maplibre-compose-material3/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/material3/util/util.desktop.kt
lib/maplibre-compose-material3/src/iosMain/kotlin/dev/sargunv/maplibrecompose/material3/util/util.ios.kt
lib/maplibre-compose-material3/src/jsMain/kotlin/dev/sargunv/maplibrecompose/material3/util/util.js.kt

Maps focused on Manhattan may want 29.9 degrees. [Sociopolitical statement maps](https://en.wikipedia.org/wiki/South-up_map_orientation) may want 180 degrees. Medieval maps may want 90 degrees.
I also moved all the utils in the material3 module to the .util package.

CompassButton: allow customizing home orientation

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/MaplibreMap.kt
lib/maplibre-compose/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/core/WebviewMap.kt

Typo fix of asyng to async in `map.asyngSetMaximumFps(maximumFps)`
This pull request primarily:
To your knowledge, are you making any breaking changes?
Do you have access to a macOS device to develop and test iOS changes?
Have you tested the changes, if applicable? On which platforms?

typo: fix asyng to async

---

gradle/libs.versions.toml
lib/maplibre-compose-material3/build.gradle.kts
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt
lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/util/htmlToAnnotatedString.kt
lib/maplibre-compose-material3/src/nonWebMain/kotlin/dev/sargunv/maplibrecompose/material3/util/htmlToAnnotatedString.nonWeb.kt
lib/maplibre-compose-material3/src/webMain/kotlin/dev/sargunv/maplibrecompose/material3/util/htmlToAnnotatedString.web.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/AttributionLink.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt
lib/maplibre-compose/src/jsMain/kotlin/dev/sargunv/maplibrecompose/core/source/Source.kt

Resolves #382 and fixes #388, but reveals oddities about how we currently lay out text on the expanding attribution bar.
Will play with it and follow up with fixes for layout in another PR

Use HtmlConverterCompose to parse HTML to an AnnotatedString for the expanding attribution button

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt

Fixes incorrect layout direction, and also avoid breaking inside an attribution (we can still do separate lines for multiple attributions if they're long enough).
I'm not super happy with the scrolling solution, but anything else I tried looked wonky in certain cases.

fix attribution text layout

---

gradle/libs.versions.toml

Reverts maplibre/maplibre-compose#418; the desktop build actually isn't working with 2.0.0

Revert "build(deps): bump io.github.kevinnzou:compose-webview-multiplatform from 1.9.40 to 2.0.0"

---

lib/maplibre-compose-material3/src/commonMain/kotlin/dev/sargunv/maplibrecompose/material3/controls/AttributionButton.kt

https://github.com/maplibre/maplibre-compose/pull/426#discussion_r2148608937
Also added an option for line breaking behavior, see https://github.com/maplibre/maplibre-compose/pull/427#issuecomment-2974324083

default text link style for attribution button

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/source/VectorSource.kt

Anywhere we pass an asset URL to MapLibre Android, we need to use the `asset://` protocol. We missed this in the tiles list on the vector source.

fix programmatic vector source not correctly handling Compose resources

---

lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/decision.kt
lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/dsl/literals.kt

Based on feedback here: https://osmus.slack.com/archives/C08SEMXV37S/p1750192486471089
This example now compiles:
```kt
switch(
input = feature.type(),
case(
listOf(GeometryType.LineString, GeometryType.MultiLineString),
const(SymbolPlacement.LineCenter),
),
fallback = const(SymbolPlacement.Point),
)
```

add some enum overloads

---

lib/maplibre-compose-expressions/src/commonMain/kotlin/dev/sargunv/maplibrecompose/expressions/Defaults.kt
lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/desktopMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt
lib/maplibre-compose/src/jsMain/kotlin/dev/sargunv/maplibrecompose/core/layer/SymbolLayer.kt

It looks like this was an oversight before:
[`icon-padding`](https://maplibre.org/maplibre-style-spec/layers/#icon-padding) is not of type `number` (like [`text-padding`](https://maplibre.org/maplibre-style-spec/layers/#text-padding)) but of type [`padding`](https://maplibre.org/maplibre-style-spec/types/#padding) (like [`icon-text-fit-padding`](https://maplibre.org/maplibre-style-spec/layers/#icon-text-fit-padding)).
It is a breaking change, as the interface changes.
I have not tested the changes. (But I can say from usage in my project that the linked documentation is correct, it is a padding, not a single value).
Also, `PaddingValues.Absolute(0.dp)` is wrong in the sense that `left` is set to `0.dp` and the rest is set to the default. (Which incidentally is also `0.dp`, so this doesn't …

Correct iconPadding type: It is a DpPaddingValue

---

lib/maplibre-compose/src/androidMain/kotlin/dev/sargunv/maplibrecompose/core/AndroidMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/MaplibreMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/MaplibreMap.kt
lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

I came accross [this issue here](https://github.com/maplibre/maplibre-compose/issues/416). Until such a map state is being created (which I assume will take a while), I would still already be happy to have some feedback on wether the map has loaded or not. This can be refined later on or expanded with different kind of callbacks or just simply added to a map state.
I simply extended the demos and looked if the callbacks are effectively propagated to the client.
**Have you tested the changes? On which platforms?**
- Android: Samsung S21 Android 12, Pixel 8 Android 15
- iOS: iPhone 16 Pro iOS 18.3

Exposed finished and failed map loading functions

---

demo-app/src/androidIosShared/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/OfflineManagerDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/AnimatedLayerDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/MarkersDemo.kt
demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/docsnippets/Layers.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/IncrementingId.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/IncrementingIdMap.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/SourceManager.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/CircleLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillExtrusionLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/FillLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HeatmapLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/HillshadeLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/LineLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/RasterLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/layer/SymbolLayer.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/SourceReferenceEffect.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberComputedSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberGeoJsonSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberImageSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberRasterSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberUserSource.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/rememberVectorSource.kt
lib/maplibre-compose/src/commonTest/kotlin/dev/sargunv/maplibrecompose/compose/StyleNodeTest.kt
lib/maplibre-compose/src/maplibreNativeMain/kotlin/dev/sargunv/maplibrecompose/compose/offline/rememberOfflinePacksSource.kt

Fixes #236 and similar crashes when recreating sources by auto generating source IDs, which ensures we never have an ID conflict and we can remove sources after adding their replacements.
Re-enabled the cluster property demo, and also testing toggling demo visibility (which used to crash)
**To your knowledge, are you making any breaking changes?**
Yes, the `id` param is no longer provided to the `remember*Source` functions.

auto assign source IDs

---

demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/docsnippets/Layers.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/engine/SourceManager.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/SourceReferenceEffect.kt
lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/compose/source/getBaseSource.kt
lib/maplibre-compose/src/commonTest/kotlin/dev/sargunv/maplibrecompose/compose/StyleNodeTest.kt

since v0.10.0, `getBaseSource` would crash when passed to a layer because we tried to add it to the style (as if it's a user source).
separately, it seems to crash if it's called before the style is fully loaded. 
fixed both by making it nullable, and only adding a reference if it's null (and therefore a user source)
```kt
getBaseSource(id = "openmaptiles")?.let { tiles ->
CircleLayer(id = "example", source = tiles, sourceLayer = "poi")
}
```
**To your knowledge, are you making any breaking changes?**
yes, `getBaseSource` now returns a nullable `Source`

fix get base source

---

lib/maplibre-compose/src/commonMain/kotlin/dev/sargunv/maplibrecompose/core/BaseStyle.kt

Compose compares "stable" types based on their equality method. This type was previously missing an `equals` overload, so different instances were always treated as different values.
Modified the demo app to repro #506

make base style a data class to fix compose stability

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

this is an attempt to resolve #508.
I added some logging and noticed the camera bounding box was being set whenever the animation stopped. We can't make that BoundingBox class as @Immutable or @Stable because it comes from a library, but we can remember the last set state ourselves and only update if it actually changes. 
Tested with the repro code from #508; animation no longer halts when keyboard collapses.

only apply bounding box when it changes, to prevent halting the camera animation without cause

---

lib/maplibre-compose/src/iosMain/kotlin/dev/sargunv/maplibrecompose/core/IosMap.kt

ios: set last bounding box

---

lib/maplibre-compose/src/commonMain/kotlin/org/maplibre/compose/layers/SymbolLayer.kt

This PR fixes #555 (partially), and documents the remaining trigger case to avoid.
Background: We convert text unit expressions (those defined in Compose SP or EM) to float expressions in either DP or EM, depending on the unit MapLibre expects for that property. Previously, we were convert first to SP, and then to DP and EM based on that SP expression. This caused the bug because:
* Each conversion multiplies the text unit expression input to it
* The first conversion only multiplies the const values, so it keeps the interpolation at the top
* But the second conversion multiplies the previous expression, causing the top level to be a multiplication instead of interpolation
Now, for text size, we convert directly to DP. Separately, we still create an SP expression to help convert other …

fix text size interpolation

---

.clang-tidy
.gitmodules
.vscode/settings.json
lib/maplibre-native-bindings-jni/CMakeLists.txt
lib/maplibre-native-bindings-jni/src/main/cpp/canvas_frontend.cpp
lib/maplibre-native-bindings-jni/src/main/cpp/canvas_metal_backend.mm
lib/maplibre-native-bindings-jni/src/main/cpp/canvas_opengl_backend.cpp
lib/maplibre-native-bindings-jni/src/main/cpp/canvas_renderer.hpp
lib/maplibre-native-bindings-jni/src/main/cpp/fix_x11_pollution.h
lib/maplibre-native-bindings-jni/src/main/cpp/jawt_context.hpp
lib/maplibre-native-bindings-jni/src/main/cpp/jni_map_observer.cpp
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/util/SharedLibraryLoader.kt

To use the prebuilt core (#568) we'll need to eliminate use of nonpublic includes.
I'm using this branch to test that build in CI.

try removing nonpublic includes

---

lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapAdapter.kt
lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/util/conversions.kt

#570
Implement the conversions required for camera state to work.

desktop: implement camera options conversions

---

lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapAdapter.kt
lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/util/conversions.kt
lib/maplibre-native-bindings-jni/src/main/cpp/conversions.cpp
lib/maplibre-native-bindings-jni/src/main/cpp/conversions.hpp
lib/maplibre-native-bindings-jni/src/main/cpp/maplibre_map.cpp
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/map/MapLibreMap.kt
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/util/EdgeInsets.kt
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/util/LatLngBounds.kt
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/util/ScreenCoordinate.kt
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/util/Size.kt

Implement `animateCameraPosition` and `getVisibleBoundingBox` by wrapping LatLngBounds in the native core.
#570

desktop: implement some camera methods by wrapping LatLngBounds

---

lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapAdapter.kt
lib/maplibre-native-bindings-jni/src/main/cpp/conversions.cpp
lib/maplibre-native-bindings-jni/src/main/cpp/conversions.hpp
lib/maplibre-native-bindings-jni/src/main/cpp/maplibre_map.cpp
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/map/BoundOptions.kt
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/map/MapLibreMap.kt

desktop: implement camera bounds

---

lib/maplibre-compose/src/desktopMain/kotlin/org/maplibre/compose/map/DesktopMapAdapter.kt
lib/maplibre-native-bindings/src/desktopMain/kotlin/org/maplibre/kmp/native/map/MapObserver.kt

desktop: update camera state during gestures
